trigger:
- main

parameters:
- name: environment
  displayName: Select Environment
  type: string
  default: dev
  values:
    - dev
    - stage
    - prod

pool:
  vmImage: ubuntu-latest

variables:
  TF_DIR: infra
  BACKEND_DIR: envs/${{ parameters.environment }}

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.6'

# ---------------- VALIDATION (SAFETY CHECK #1) ----------------
- script: terraform fmt -check
  displayName: Terraform Format Check
  workingDirectory: $(TF_DIR)

- script: terraform validate
  displayName: Terraform Validate
  workingDirectory: $(TF_DIR)

# ---------------- INIT ----------------
- script: |
    terraform init \
      -backend-config=$(BACKEND_DIR)/backend.tf
  displayName: Terraform Init
  workingDirectory: $(TF_DIR)
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)

# ---------------- PLAN (SAFETY CHECK #2) ----------------
- script: |
    terraform plan \
      -var="environment=${{ parameters.environment }}" \
      -var="resource_group_name=azure-terraform" \
      -out=tfplan
  displayName: Terraform Plan
  workingDirectory: $(TF_DIR)

# ---------------- MANUAL APPROVAL FOR PROD ----------------
- task: ManualValidation@0
  condition: eq('${{ parameters.environment }}', 'prod')
  inputs:
    instructions: 'Approve Terraform Apply for PROD'
    timeoutInMinutes: 60

# ---------------- APPLY ----------------
- script: terraform apply -auto-approve tfplan
  displayName: Terraform Apply
  workingDirectory: $(TF_DIR)
